Goriber_BookShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('books/', include('book.urls')),
    path('author/', include('author.urls')),
    path('transactions/', include('transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts.views import UserRegisterView, UserLoginView, UserProfileView, UserLogoutView, UserChangePasswordView, DepositMoneyView, UserUpdateProfileView

app_name= 'accounts'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('update-profile/', UserUpdateProfileView.as_view(), name='update_profile'),
    path('change-password/', UserChangePasswordView.as_view(), name='change_password'),
    path('deposit/', DepositMoneyView.as_view(), name='deposit'),
]

book/urls.py
from django.urls import path
from book.views import BookDetailsView, BorrowBookWithMoney, BorrowBookWithCoins, ReturnBook

urlpatterns = [
    path('book/<int:pk>/', BookDetailsView.as_view(), name='book_details'),
    path('borrow-with-money/<int:pk>/', BorrowBookWithMoney.as_view(), name='borrow_with_money'),
    path('borrow-with-coins/<int:pk>/', BorrowBookWithCoins.as_view(), name='borrow_with_coins'),
    path('return/<int:pk>/', ReturnBook.as_view(), name='return_book'),
]

core/urls.py
from django.urls import path
from core.views import home_view

urlpatterns = [
    path("", home_view, name="home"),
    path("category/<slug:slug>/", home_view, name="category"),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render, get_object_or_404
from book.models import Book, Category
from author.models import Author
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string


def send_email(user, amount, subject, template):
    message = render_to_string(template,{
        'user' : user,
        'amount' : amount
    })

    send_email = EmailMultiAlternatives(subject, '', to=[user.email])
    send_email.attach_alternative(message, 'text/html')
    send_email.send()



def home_view(request, slug = None):
    books = Book.objects.all()
    categories = Category.objects.all()

    authors = Author.objects.order_by('-popularity')
    top_10_authors = authors[:10]
    x = 1
    for author in authors:
        author.rank = x
        author.save()
        x += 1

    curr_category = None

    top_selling = Book.objects.order_by('-borrow_count')[:10]

    if slug is not None:
        category = get_object_or_404(Category, slug=slug)
        curr_category = category.name
        books = Book.objects.filter(categories=category)
        return render(request, 'core/index.html', {'books' : books, 'categories' : categories, 'curr_category' : curr_category, 'book_title' : 'Showing Results for ', 'top_selling' : top_selling, 'top_authors' : top_10_authors})
    
    return render(request, 'core/index.html', {'books' : books, 'categories' : categories, 'curr_category' : curr_category, 'book_title' : 'Newly Added Books', 'top_selling' : top_selling, 'top_authors' : top_10_authors})

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.19/dist/full.min.css" rel="stylesheet" type="text/css" />
    <link href="https://unpkg.com/tailwindcss@2.0.1/dist/tailwind.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" />

    <style>
      img{
        width: 100%;
        height: 100%;
      }
    {% block style %}

    {% endblock style %}
    </style>
</head>
<body>
    <header>
        {% include "core/navbar.html" %}
        <div class="pb-16"></div>
    </header>
    <main class="min-h-screen">
      {% if messages %}
    {% for message in messages %}
    <div class="toast z-50">
      <div role="alert" class="alert alert-warning m-5">
        <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        class="h-6 w-6 shrink-0 stroke-current">
        <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
        </svg>  
        <span>{{message}}</span>
      </div>
    </div>
    {% endfor %}
{% endif %}
      {% block main %}
      {% endblock main %}
    </main>
    <footer class="footer bg-base-300 text-base-content p-10">
        <nav>
          <h6 class="footer-title">Services</h6>
          <a class="link link-hover">Branding</a>
          <a class="link link-hover">Design</a>
          <a class="link link-hover">Marketing</a>
          <a class="link link-hover">Advertisement</a>
        </nav>
        <nav>
          <h6 class="footer-title">Company</h6>
          <a class="link link-hover">About us</a>
          <a class="link link-hover">Contact</a>
          <a class="link link-hover">Jobs</a>
          <a class="link link-hover">Press kit</a>
        </nav>
        <nav>
          <h6 class="footer-title">Social</h6>
          <div class="grid grid-flow-col gap-4">
            <a>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                class="fill-current">
                <path
                  d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
              </svg>
            </a>
            <a>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                class="fill-current">
                <path
                  d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
              </svg>
            </a>
            <a>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                class="fill-current">
                <path
                  d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
              </svg>
            </a>
          </div>
          <p class="font-bold mb-2 underline"><a>Copyright ©{% now 'Y' %}, Goriber-BookShop.</a></p>
        </nav>
      </footer>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Home - Goriber-BookShop{% endblock title %}

{% block main %}
<div class="content grid grid-cols-12 gap-6 p-4">
  {% comment %} <!-- Sidebar with categories --> {% endcomment %}
  <div class="left col-span-12 md:col-span-2 bg-white shadow-lg rounded-lg p-4">
    <h2 class="text-lg font-semibold mb-4 text-gray-700"><i class="fa-solid fa-filter"></i> Categories</h2>
      {% for category in categories %}
        <a class="badge badge-outline m-2 p-3" href="{% url 'category' slug=category.slug %}">{{category.name}}</a>
      {% endfor %}
  </div>

  {% comment %} <!-- Main Content --> {% endcomment %}
  <div class="right col-span-12 md:col-span-10">

    {% comment %} <!-- Carousel --> {% endcomment %}
    <div class="carousel w-full h-64 rounded-lg shadow-lg overflow-hidden border border-black">
      <div class="carousel-item w-full">
        <img src="{% static 'slides/2.webp' %}" class="w-full h-full object-cover" alt="Slide 1" />
      </div>
      <div class="carousel-item w-full">
        <img src="{% static 'slides/1.webp' %}" class="w-full h-full object-cover" alt="Slide 2" />
      </div>
    </div>

    {% comment %} <!-- Book Cards --> {% endcomment %}
    <h1 class="text-3xl mt-8 mb-2 font-bold"><i class="fa-solid fa-bookmark"></i> {{book_title}} {% if curr_category %}<a href="{% url 'home' %}" class="text-3xl p-2 tooltip bg-gray-300 rounded-3xl" data-tip="Reset Filter">{{curr_category}} <i class="fa-solid fa-xmark"></i></a>{% endif %}</h1>
    <hr>
    <div class="flex flex-wrap gap-6 mt-6">
      {% for book in books %}
      <div class="bg-white shadow-md hover:shadow-lg transition-shadow duration-300 rounded-lg overflow-hidden w-72 h-96">
        <a href="{% url 'book_details' book.id %}">
          <div class="flex justify-center">
            <img src="{{ book.photo.url }}" alt="{{ book.title }}" class="w-52 h-64 object-cover"/>
          </div>
          <div class="card-body p-4">
            <h2 class="text-lg font-semibold text-gray-800">{{ book.title|truncatechars:50 }}</h2>
            <h3 class="text-md font-bold text-black">Tk. {{book.price}}</h3>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>

    {% comment %} top 10 authors  {% endcomment %}
    <h1 class="text-3xl mt-8 mb-2 font-bold">Shop by Popular Author <i class="fa-solid fa-fire-flame-curved"></i></h1>
    <hr>
    <div class="flex gap-3 p-2">
      {% for author in top_authors %}
          <a href="{% url 'author_profile' author.id %}"><img src="{{author.photo.url}}" class="rounded-full border border-black w-32" /></a>
      {% endfor %}
    </div>

    {% comment %} top selling  {% endcomment %}
    <h1 class="text-3xl mt-8 mb-2 font-bold">Top Selling <i class="fa-solid fa-arrow-trend-up"></i></h1>
    <hr>
    
    <div class="flex flex-wrap gap-6 mt-6">
      {% for book in top_selling %}
      <div class="bg-white shadow-md hover:shadow-lg transition-shadow duration-300 rounded-lg overflow-hidden w-72 h-96 my-3">
        <a href="{% url 'book_details' book.id %}">
          <div class="flex justify-center">
            <img src="{{ book.photo.url }}" alt="{{ book.title }}" class="w-52 h-64 object-cover"/>
          </div>
          <div class="card-body p-4">
            <h2 class="text-lg font-semibold text-gray-800">{{ book.title|truncatechars:50 }}</h2>
            <h3 class="text-md font-bold text-black">Tk. {{book.price}}</h3>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock main %}

core/templates/core/navbar.html
{% load static %}

<nav>
    <div class="navbar bg-base-300 text-base-content fixed z-40">
        <div class="flex-1">
          <a class="w-12" href="{% url 'home' %}"><img src="{% static 'nav/book.png' %}" alt="logo"></a>
          <ul class="menu menu-horizontal px-1 text-black font-bold">
              <li>
                <details>
                  <summary>Menu</summary>
                  <ul class="bg-base-200 rounded-t-none p-2 shadow-lg z-50">
                    {% if user.is_authenticated %}
                    <kbd class="kbd md:hidden">{{user.first_name}} ${{user.account.balance}}</kbd>
                    <li><a href="{% url 'accounts:deposit' %}">Deposit</a></li>
                    <li><a href="{% url 'transaction_report' %}">Report</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}"><i class="fa-solid fa-address-card"></i> Register/Login</a></li>
                    {% endif %}
                  </ul>
                </details>
              </li>
            </ul>
        </div>
        <div class="flex-none">
          {% if user.is_authenticated %}
          <div class="hidden md:inline"><kbd class="kbd">{{user.first_name}} ${{user.account.balance}}</kbd></div>
          {% endif %}
          <div class="dropdown dropdown-end">
            <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
              <div class="w-10 rounded-full">
                <img
                  alt="profile"
                  src="{% static 'nav/default.png' %}" />
              </div>
            </div>
            <ul
              tabindex="0"
              class="menu menu-sm dropdown-content bg-base-200 rounded-box mt-3 w-52 p-2 shadow-lg z-50">
              {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:profile' %}"><i class="fa-solid fa-user"></i> Profile</a></li>
              <li><a href="{% url 'accounts:update_profile' %}"><i class="fa-solid fa-gear"></i> Settings</a></li>
              <li><a href="{% url 'accounts:logout' %}"><i class="fa-solid fa-right-from-bracket"></i> Logout</a></li>
              {% else %}
              <li><a href="{% url 'accounts:login' %}"><i class="fa-solid fa-address-card"></i> Register/Login</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
</nav>